version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/SpeedtestWatcher.Core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/SpeedtestWatcher.Infrastructure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/SpeedtestWatcher.Web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/tests/SpeedtestWatcher.Tests"
    schedule:
      interval: "weekly"
