<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SpeedtestWatcher.UnitTests" />
    <InternalsVisibleTo Include="SpeedtestWatcher.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SpeedtestWatcher.Application\SpeedtestWatcher.Application.csproj" />
  </ItemGroup>

</Project>
