// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedtestWatcher.Infrastructure.Data;

#nullable disable

namespace SpeedtestWatcher.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SpeedtestWatcherDbContext))]
    partial class SpeedtestWatcherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SpeedtestWatcher.Core.Models.ConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Core.Models.IntegrationData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("ActivityFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("activityFailed");

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("data");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Untitled")
                        .HasColumnName("displayName");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastActivity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("integration_data", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Core.Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Download")
                        .HasColumnType("REAL")
                        .HasColumnName("download");

                    b.Property<int>("Ping")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ping");

                    b.Property<double>("Upload")
                        .HasColumnType("REAL")
                        .HasColumnName("upload");

                    b.HasKey("Id");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Core.Models.Speedtest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<double>("Download")
                        .HasColumnType("REAL")
                        .HasColumnName("download");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<bool?>("Healthy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("healthy");

                    b.Property<double?>("Jitter")
                        .HasColumnType("REAL")
                        .HasColumnName("jitter");

                    b.Property<int>("Ping")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ping");

                    b.Property<string>("ResultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resultId");

                    b.Property<string>("ServerHost")
                        .HasColumnType("TEXT")
                        .HasColumnName("serverHost");

                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("serverId");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("serverName");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.Property<double?>("ThresholdDownload")
                        .HasColumnType("REAL")
                        .HasColumnName("thresholdDownload");

                    b.Property<int?>("ThresholdPing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("thresholdPing");

                    b.Property<double?>("ThresholdUpload")
                        .HasColumnType("REAL")
                        .HasColumnName("thresholdUpload");

                    b.Property<int>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("auto")
                        .HasColumnName("type");

                    b.Property<double>("Upload")
                        .HasColumnType("REAL")
                        .HasColumnName("upload");

                    b.HasKey("Id");

                    b.ToTable("speedtests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
