// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedtestWatcher.Application.Storage;

#nullable disable

namespace SpeedtestWatcher.Application.Storage.Migrations
{
    [DbContext(typeof(SpeedtestWatcherDbContext))]
    [Migration("20260923103325_AddBufferbloatByDirection")]
    partial class AddBufferbloatByDirection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SpeedtestWatcher.Application.Integrations.IntegrationData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("ActivityFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("activityFailed");

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("data");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Untitled")
                        .HasColumnName("displayName");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastActivity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("integration_data", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Application.Monitoring.Outage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("endedAt");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("startedAt");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("outages", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Application.Monitoring.ProbeRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Answered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("answered");

                    b.Property<int>("Asked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("asked");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT")
                        .HasColumnName("at");

                    b.Property<bool>("DuringTest")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duringTest");

                    b.Property<double?>("FastestMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("fastestMs");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passed");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("probe_rounds", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Application.Monitoring.WatchSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastSeenAt");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("startedAt");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("watch_sessions", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Application.Recommendations.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Download")
                        .HasColumnType("REAL")
                        .HasColumnName("download");

                    b.Property<int>("Ping")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ping");

                    b.Property<double>("Upload")
                        .HasColumnType("REAL")
                        .HasColumnName("upload");

                    b.HasKey("Id");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Application.Settings.ConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("SpeedtestWatcher.Application.Speedtests.Speedtest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("Bufferbloat")
                        .HasColumnType("REAL")
                        .HasColumnName("bufferbloat");

                    b.Property<double?>("BufferbloatDown")
                        .HasColumnType("REAL")
                        .HasColumnName("bufferbloatDown");

                    b.Property<double?>("BufferbloatUp")
                        .HasColumnType("REAL")
                        .HasColumnName("bufferbloatUp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<double>("Download")
                        .HasColumnType("REAL")
                        .HasColumnName("download");

                    b.Property<long?>("DownloadBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("downloadBytes");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<bool?>("Healthy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("healthy");

                    b.Property<double?>("Jitter")
                        .HasColumnType("REAL")
                        .HasColumnName("jitter");

                    b.Property<double?>("LatencyIdle")
                        .HasColumnType("REAL")
                        .HasColumnName("latencyIdle");

                    b.Property<double?>("LatencyLoaded")
                        .HasColumnType("REAL")
                        .HasColumnName("latencyLoaded");

                    b.Property<double?>("LatencyLoadedTail")
                        .HasColumnType("REAL")
                        .HasColumnName("latencyLoadedTail");

                    b.Property<double?>("PacketLoss")
                        .HasColumnType("REAL")
                        .HasColumnName("packetLoss");

                    b.Property<int>("Ping")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ping");

                    b.Property<string>("PublicIp")
                        .HasColumnType("TEXT")
                        .HasColumnName("publicIp");

                    b.Property<string>("ResultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resultId");

                    b.Property<string>("ServerHost")
                        .HasColumnType("TEXT")
                        .HasColumnName("serverHost");

                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("serverId");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("serverName");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.Property<double?>("ThresholdBufferbloat")
                        .HasColumnType("REAL")
                        .HasColumnName("thresholdBufferbloat");

                    b.Property<double?>("ThresholdDownload")
                        .HasColumnType("REAL")
                        .HasColumnName("thresholdDownload");

                    b.Property<double?>("ThresholdPacketLoss")
                        .HasColumnType("REAL")
                        .HasColumnName("thresholdPacketLoss");

                    b.Property<int?>("ThresholdPing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("thresholdPing");

                    b.Property<double?>("ThresholdUpload")
                        .HasColumnType("REAL")
                        .HasColumnName("thresholdUpload");

                    b.Property<int>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("auto")
                        .HasColumnName("type");

                    b.Property<double>("Upload")
                        .HasColumnType("REAL")
                        .HasColumnName("upload");

                    b.Property<long?>("UploadBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uploadBytes");

                    b.HasKey("Id");

                    b.ToTable("speedtests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
